/**
 * The Launchpad design gallery — 18 in-house design directions, drawn and
 * owned here (nothing is fetched from a third-party inspiration service).
 * Each entry is the documented template shape plus the tokens the generator
 * needs to honour the direction: typography, effects, layout kind.
 */
const { siteletThumb } = require('./sitelet');

const D = (design) => ({
  ...design,
  thumbnailUrl: design.thumbnailUrl || siteletThumb({
    palette: design.colorPalette,
    kind: design.preview.kind,
    seed: design.seed || 3,
    sections: design.preview.sections,
  }),
});

const DESIGNS = [
  D({
    id: 'dark-luxury-01',
    name: 'Midnight Edit',
    category: 'product',
    categories: ['product', 'personal-brand', 'portfolio', 'other'],
    styleTags: ['dark', 'minimal', 'large-typography', 'editorial'],
    layoutHints: 'Full-bleed hero image, oversized product photography, sparse nav',
    colorPalette: ['#08080a', '#f6f6f7', '#c7c7cf'],
    preview: { kind: 'hero-fullbleed', sections: ['hero', 'productShowcase', 'gallery', 'cta'] },
    typography: { heading: 'display', body: 'sans', scale: 1.18, tracking: '-0.035em', weight: 600 },
    effects: ['grain', 'slow-fade'],
    spacing: 'roomy',
    seed: 11,
  }),
  D({
    id: 'bold-editorial-02',
    name: 'Bold Editorial',
    category: 'personal-brand',
    categories: ['personal-brand', 'business', 'portfolio', 'campaign', 'other'],
    styleTags: ['bold typography', 'high-contrast', 'magazine grid'],
    layoutHints: 'Oversized masthead headline, hairline rules, two-column editorial body',
    colorPalette: ['#0d0d10', '#ffffff', '#ff5a36'],
    preview: { kind: 'magazine', sections: ['hero', 'about', 'testimonials', 'cta'] },
    typography: { heading: 'display', body: 'serif', scale: 1.3, tracking: '-0.045em', weight: 700 },
    effects: ['rules'],
    spacing: 'roomy',
    seed: 23,
  }),
  D({
    id: 'soft-luxury-03',
    name: 'Soft Luxury',
    category: 'business',
    categories: ['business', 'restaurant', 'personal-brand', 'other'],
    styleTags: ['warm', 'muted', 'serif', 'light'],
    layoutHints: 'Light bone background, serif display, image pairs with generous captions',
    colorPalette: ['#f5f2ec', '#1b1a17', '#8a6f4c'],
    preview: { kind: 'hero-split', sections: ['hero', 'features', 'gallery', 'contact'] },
    typography: { heading: 'serif', body: 'sans', scale: 1.1, tracking: '-0.015em', weight: 500 },
    effects: ['soft-shadow'],
    spacing: 'roomy',
    seed: 31,
  }),
  D({
    id: 'futuristic-04',
    name: 'Nova Grid',
    category: 'product',
    categories: ['product', 'startup', 'app', 'campaign'],
    styleTags: ['futuristic', 'dark', 'purple accent', 'mono labels'],
    layoutHints: 'Grid-lined dark hero, monospace micro-labels, glowing edge highlights',
    colorPalette: ['#06070c', '#eaf6ff', '#8b5cf6'],
    preview: { kind: 'hero-centered', sections: ['hero', 'countdown', 'features', 'waitlist'] },
    typography: { heading: 'grotesk', body: 'sans', scale: 1.2, tracking: '-0.03em', weight: 700 },
    effects: ['grid', 'glow', 'mono-labels'],
    spacing: 'airy',
    seed: 41,
  }),
  D({
    id: 'index-minimal-05',
    name: 'Quiet Index',
    category: 'portfolio',
    categories: ['portfolio', 'personal-brand', 'business', 'app'],
    styleTags: ['minimal', 'whitespace', 'type-led', 'light'],
    layoutHints: 'Numbered index of work, tiny nav, one project per row at full width',
    colorPalette: ['#fafafa', '#141414', '#0f766e'],
    preview: { kind: 'stack-rows', sections: ['hero', 'gallery', 'about', 'contact'] },
    typography: { heading: 'sans', body: 'sans', scale: 1.05, tracking: '-0.01em', weight: 500 },
    effects: ['index-numbers'],
    spacing: 'roomy',
    seed: 53,
  }),
  D({
    id: 'neon-stage-06',
    name: 'Neon Stage',
    category: 'music',
    categories: ['music', 'event', 'community'],
    styleTags: ['dark', 'glow', 'big type', 'night'],
    layoutHints: 'Artwork left, type right, glow rings, tracklist rows with hover scrub',
    colorPalette: ['#05040a', '#f7f4ff', '#d946ef'],
    preview: { kind: 'hero-split', sections: ['hero', 'tracklist', 'countdown', 'preSave'] },
    typography: { heading: 'display', body: 'sans', scale: 1.26, tracking: '-0.04em', weight: 800 },
    effects: ['glow', 'grain'],
    spacing: 'airy',
    seed: 61,
  }),
  D({
    id: 'festival-07',
    name: 'Festival Poster',
    category: 'event',
    categories: ['event', 'community', 'campaign', 'music'],
    styleTags: ['bold', 'poster', 'high contrast', 'stacked names'],
    layoutHints: 'Poster-style hero, stacked line-up names, ticket slab, countdown band',
    colorPalette: ['#0b0b0d', '#ffffff', '#facc15'],
    preview: { kind: 'hero-centered', sections: ['hero', 'countdown', 'speakers', 'tickets'] },
    typography: { heading: 'display', body: 'sans', scale: 1.34, tracking: '-0.05em', weight: 900 },
    effects: ['marquee', 'outline-type'],
    spacing: 'tight',
    seed: 71,
  }),
  D({
    id: 'seed-dark-08',
    name: 'Seed Deck',
    category: 'startup',
    categories: ['startup', 'app', 'business'],
    styleTags: ['dark', 'technical', 'data-forward', 'mono'],
    layoutHints: 'Metric strip under hero, product screenshot in device frame, three-column proof',
    colorPalette: ['#080a0d', '#e7edf3', '#22d3ee'],
    preview: { kind: 'hero-centered', sections: ['hero', 'stats', 'features', 'pricing'] },
    typography: { heading: 'grotesk', body: 'sans', scale: 1.12, tracking: '-0.025em', weight: 600 },
    effects: ['mono-labels', 'grid'],
    spacing: 'airy',
    seed: 83,
  }),
  D({
    id: 'clean-slate-09',
    name: 'Clean Slate',
    category: 'app',
    categories: ['app', 'startup', 'business', 'community'],
    styleTags: ['light', 'friendly', 'rounded', 'pastel accent'],
    layoutHints: 'Soft light background, phone mockup centred, rounded feature cards',
    colorPalette: ['#f6f7fb', '#101323', '#4f46e5'],
    preview: { kind: 'hero-split', sections: ['hero', 'features', 'testimonials', 'cta'] },
    typography: { heading: 'sans', body: 'sans', scale: 1.1, tracking: '-0.02em', weight: 650 },
    effects: ['soft-shadow'],
    spacing: 'airy',
    radius: 20,
    seed: 89,
  }),
  D({
    id: 'noir-commerce-10',
    name: 'Noir Commerce',
    category: 'product',
    categories: ['product', 'business'],
    styleTags: ['noir', 'studio light', 'product-first', 'monochrome'],
    layoutHints: 'Black studio backdrop, product centred, price and buy as a thin sticky bar',
    colorPalette: ['#000000', '#f2f2f2', '#a3a3a3'],
    preview: { kind: 'hero-fullbleed', sections: ['hero', 'productShowcase', 'features', 'faq'] },
    typography: { heading: 'display', body: 'sans', scale: 1.15, tracking: '-0.03em', weight: 700 },
    effects: ['vignette'],
    spacing: 'roomy',
    seed: 97,
  }),
  D({
    id: 'tasting-menu-11',
    name: 'Tasting Menu',
    category: 'restaurant',
    categories: ['restaurant', 'business', 'event'],
    styleTags: ['warm dark', 'serif', 'appetite', 'menu columns'],
    layoutHints: 'Room-at-night hero, two-column menu with dotted leaders, gallery strip',
    colorPalette: ['#12100e', '#f8f3ea', '#c99b6a'],
    preview: { kind: 'hero-fullbleed', sections: ['hero', 'menu', 'gallery', 'contact'] },
    typography: { heading: 'serif', body: 'serif', scale: 1.08, tracking: '-0.01em', weight: 500 },
    effects: ['rules'],
    spacing: 'roomy',
    seed: 103,
  }),
  D({
    id: 'movement-12',
    name: 'The Movement',
    category: 'campaign',
    categories: ['campaign', 'community', 'event'],
    styleTags: ['activist', 'bold', 'red accent', 'urgent'],
    layoutHints: 'Full-width statement headline, live counters, hard-edged sign-up slab',
    colorPalette: ['#0c0c0e', '#ffffff', '#ef4444'],
    preview: { kind: 'magazine', sections: ['hero', 'stats', 'about', 'waitlist'] },
    typography: { heading: 'display', body: 'sans', scale: 1.3, tracking: '-0.05em', weight: 800 },
    effects: ['marquee', 'outline-type'],
    spacing: 'tight',
    seed: 109,
  }),
  D({
    id: 'gallery-white-13',
    name: 'Gallery White',
    category: 'portfolio',
    categories: ['portfolio', 'personal-brand', 'product', 'music'],
    styleTags: ['gallery', 'white space', 'tiny type', 'art-first'],
    layoutHints: 'White cube walls, images at varying sizes, micro captions, no chrome',
    colorPalette: ['#ffffff', '#15151a', '#b91c1c'],
    preview: { kind: 'grid-cards', sections: ['hero', 'gallery', 'about', 'footer'] },
    typography: { heading: 'sans', body: 'sans', scale: 1.0, tracking: '0em', weight: 400 },
    effects: ['micro-captions'],
    spacing: 'roomy',
    seed: 113,
  }),
  D({
    id: 'members-only-14',
    name: 'Members Only',
    category: 'community',
    categories: ['community', 'business', 'app'],
    styleTags: ['dark', 'gold accent', 'exclusive', 'serif'],
    layoutHints: 'Invitation-tone hero, benefits in ledger rows, join slab with position number',
    colorPalette: ['#0a0b0d', '#f4efe6', '#c9a227'],
    preview: { kind: 'hero-centered', sections: ['hero', 'features', 'stats', 'cta'] },
    typography: { heading: 'serif', body: 'sans', scale: 1.12, tracking: '-0.015em', weight: 600 },
    effects: ['rules', 'soft-shadow'],
    spacing: 'roomy',
    seed: 127,
  }),
  D({
    id: 'terminal-15',
    name: 'Terminal Cool',
    category: 'app',
    categories: ['app', 'startup', 'personal-brand'],
    styleTags: ['dark', 'mono', 'developer', 'green accent'],
    layoutHints: 'Monospace hero with prompt line, code-block features, terminal-style gallery',
    colorPalette: ['#070a09', '#d7ffe6', '#4ade80'],
    preview: { kind: 'hero-centered', sections: ['hero', 'features', 'pricing', 'faq'] },
    typography: { heading: 'mono', body: 'mono', scale: 1.06, tracking: '-0.01em', weight: 600 },
    effects: ['mono-labels', 'scanline'],
    spacing: 'tight',
    radius: 8,
    seed: 131,
  }),
  D({
    id: 'sunset-openair-16',
    name: 'Sunset Open Air',
    category: 'event',
    categories: ['event', 'music', 'community', 'campaign'],
    styleTags: ['gradient', 'friendly', 'outdoor', 'rounded'],
    layoutHints: 'Sunset gradient hero, rounded info tiles, schedule as timeline',
    colorPalette: ['#160f22', '#fff7ed', '#fb923c'],
    preview: { kind: 'hero-centered', sections: ['hero', 'schedule', 'speakers', 'tickets'] },
    typography: { heading: 'display', body: 'sans', scale: 1.2, tracking: '-0.03em', weight: 750 },
    effects: ['aurora'],
    spacing: 'airy',
    radius: 22,
    seed: 139,
  }),
  D({
    id: 'founder-note-17',
    name: 'Founder Note',
    category: 'startup',
    categories: ['startup', 'business', 'campaign'],
    styleTags: ['light', 'letter-like', 'trust', 'typographic'],
    layoutHints: 'Letter-style hero, proof logos strip, milestones in a left rail',
    colorPalette: ['#fbfbf9', '#16181d', '#1d4ed8'],
    preview: { kind: 'stack-rows', sections: ['hero', 'problem', 'solution', 'pricing'] },
    typography: { heading: 'serif', body: 'sans', scale: 1.08, tracking: '-0.01em', weight: 500 },
    effects: ['rules'],
    spacing: 'roomy',
    seed: 149,
  }),
  D({
    id: 'afterhours-18',
    name: 'After Hours',
    category: 'music',
    categories: ['music', 'event', 'personal-brand'],
    styleTags: ['moody', 'film grain', 'low light', 'purple accent'],
    layoutHints: 'Dim live photography, wide letterbox hero, release countdown in mono',
    colorPalette: ['#08060c', '#efe9ff', '#a78bfa'],
    preview: { kind: 'hero-fullbleed', sections: ['hero', 'artistStory', 'countdown', 'social'] },
    typography: { heading: 'display', body: 'sans', scale: 1.22, tracking: '-0.04em', weight: 700 },
    effects: ['grain', 'vignette', 'letterbox'],
    spacing: 'roomy',
    seed: 151,
  }),
];

/** Shared "everywhere" designs get appended so no category looks empty. */
const UNIVERSAL = ['dark-luxury-01', 'bold-editorial-02', 'gallery-white-13', 'index-minimal-05'];

function designsForCategory(category) {
  const matches = DESIGNS.filter((d) => (d.categories || [d.category]).includes(category));
  const seen = new Set(matches.map((d) => d.id));
  const extra = UNIVERSAL.filter((id) => !seen.has(id)).map((id) => DESIGNS.find((d) => d.id === id));
  return [...matches, ...extra].filter(Boolean);
}

const designById = (id) => DESIGNS.find((d) => d.id === id) || null;

module.exports = { DESIGNS, designsForCategory, designById };
