/**
 * Launchpad catalog — the product's curated knowledge base.
 * Website types, the in-house design gallery and per-type asset plans all live
 * here so the API is the single source of truth (the web app fetches it).
 */

const icon = (name) => name;

/** Every type declares: sections it defaults to, the assets it asks for, tone. */
const WEBSITE_TYPES = [
  {
    id: 'product',
    label: 'Product',
    emoji: '📦',
    blurb: 'Something you make, sell or ship — with a story worth telling.',
    icon: icon('Package'),
    tone: 'confident, tactile, desire-driven',
    heroLayout: 'fullbleed',
    sections: ['hero', 'productShowcase', 'features', 'gallery', 'testimonials', 'pricing', 'cta', 'footer'],
    assets: [
      { key: 'logo', label: 'Brand logo', hint: 'Transparent PNG or SVG', recommendedSections: ['nav', 'footer'] },
      { key: 'campaign', label: 'Main campaign image', hint: 'Hero shot, at least 1600px wide', recommendedSections: ['hero'] },
      { key: 'product', label: 'Product photos', hint: 'One per product — clean background or in use', recommendedSections: ['productShowcase', 'gallery'] },
      { key: 'lifestyle', label: 'Lifestyle / model photos', hint: 'The product in the real world', recommendedSections: ['gallery', 'about'] },
      { key: 'detail', label: 'Detail or material shots', hint: 'Texture, packaging, close-ups', recommendedSections: ['gallery'] },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    emoji: '🏢',
    blurb: 'A service, studio or local business that needs to be trusted fast.',
    icon: icon('Building2'),
    tone: 'creditable, warm, specific',
    heroLayout: 'split',
    sections: ['hero', 'about', 'features', 'team', 'testimonials', 'pricing', 'contact', 'footer'],
    assets: [
      { key: 'logo', label: 'Company logo', hint: 'Transparent PNG or SVG', recommendedSections: ['nav', 'footer'] },
      { key: 'hero', label: 'Hero photo', hint: 'Your space, team or best work', recommendedSections: ['hero'] },
      { key: 'work', label: 'Project / service photos', hint: '3–6 images of real work', recommendedSections: ['gallery', 'features'] },
      { key: 'team', label: 'Team photos', hint: 'Faces build trust', recommendedSections: ['team'] },
      { key: 'interior', label: 'Interior or location photos', hint: 'Where clients find you', recommendedSections: ['about', 'contact'] },
    ],
  },
  {
    id: 'startup',
    label: 'Startup',
    emoji: '🚀',
    blurb: 'A company raising, launching or entering a market.',
    icon: icon('Rocket'),
    tone: 'precise, ambitious, evidence-led',
    heroLayout: 'centered',
    sections: ['hero', 'problem', 'solution', 'features', 'productShowcase', 'testimonials', 'pricing', 'cta', 'footer'],
    assets: [
      { key: 'logo', label: 'Company logo', hint: 'SVG preferred', recommendedSections: ['nav', 'footer'] },
      { key: 'product', label: 'Product screenshot', hint: 'The real UI, not a mockup', recommendedSections: ['hero', 'productShowcase'] },
      { key: 'screens', label: 'App / feature screenshots', hint: 'One per feature', recommendedSections: ['productShowcase', 'features'] },
      { key: 'mockups', label: 'Product mockups', hint: 'Device shots, posters, hardware', recommendedSections: ['gallery'] },
      { key: 'team', label: 'Founder / team photos', hint: 'Investors and customers both look', recommendedSections: ['team', 'about'] },
      { key: 'brand', label: 'Brand images', hint: 'Anything else on-brand', recommendedSections: ['gallery'] },
    ],
  },
  {
    id: 'event',
    label: 'Event',
    emoji: '🎟️',
    blurb: 'A conference, party, wedding, screening or meetup with a date.',
    icon: icon('CalendarDays'),
    tone: 'energetic, concrete, FOMO-aware',
    heroLayout: 'fullbleed',
    sections: ['hero', 'countdown', 'eventDetails', 'speakers', 'schedule', 'gallery', 'tickets', 'faq', 'cta', 'footer'],
    assets: [
      { key: 'poster', label: 'Event poster / key art', hint: 'The image you would print', recommendedSections: ['hero'] },
      { key: 'venue', label: 'Venue photos', hint: 'Stage, room, exterior', recommendedSections: ['eventDetails', 'gallery'] },
      { key: 'speakers', label: 'Speaker photos', hint: 'Square headshots work best', recommendedSections: ['speakers'] },
      { key: 'sponsors', label: 'Sponsor logos', hint: 'White or transparent', recommendedSections: ['logos'] },
      { key: 'past', label: 'Previous event photos', hint: 'Proof that it slaps', recommendedSections: ['gallery'] },
    ],
  },
  {
    id: 'app',
    label: 'App',
    emoji: '📱',
    blurb: 'A mobile or web app you want people to install or try.',
    icon: icon('Smartphone'),
    tone: 'crisp, benefit-first, playful',
    heroLayout: 'split',
    sections: ['hero', 'features', 'productShowcase', 'testimonials', 'pricing', 'faq', 'cta', 'footer'],
    assets: [
      { key: 'logo', label: 'App icon', hint: '1024×1024 square', recommendedSections: ['nav', 'hero'] },
      { key: 'screens', label: 'App screenshots', hint: '3–5 key screens', recommendedSections: ['productShowcase', 'hero'] },
      { key: 'mockups', label: 'Device mockups', hint: 'Screens in context', recommendedSections: ['gallery'] },
      { key: 'video', label: 'Demo video or GIF', hint: 'Under 20 seconds', recommendedSections: ['video'] },
      { key: 'press', label: 'Press or award badges', hint: 'Logos of outlets that covered you', recommendedSections: ['logos'] },
    ],
  },
  {
    id: 'music',
    label: 'Music',
    emoji: '🎧',
    blurb: 'A release, EP, album or artist page.',
    icon: icon('Disc3'),
    tone: 'atmospheric, intimate, bold',
    heroLayout: 'fullbleed',
    sections: ['hero', 'album', 'tracklist', 'artistStory', 'countdown', 'preSave', 'gallery', 'social', 'footer'],
    assets: [
      { key: 'artist', label: 'Artist / profile photo', hint: 'Moody works better than posed', recommendedSections: ['artistStory', 'hero'] },
      { key: 'artwork', label: 'Album / single artwork', hint: 'Square, high contrast', recommendedSections: ['hero', 'album'] },
      { key: 'live', label: 'Performance photos', hint: 'Crowd, stage, backstage', recommendedSections: ['gallery', 'artistStory'] },
      { key: 'video', label: 'Music video or visual artwork', hint: 'Link or poster frame', recommendedSections: ['video'] },
      { key: 'logos', label: 'Label / feature artist logos', hint: 'For the credits row', recommendedSections: ['footer'] },
    ],
  },
  {
    id: 'personal-brand',
    label: 'Personal Brand',
    emoji: '🪪',
    blurb: 'You — the offer, the point of view, the inbox.',
    icon: icon('UserRound'),
    tone: 'first-person, direct, human',
    heroLayout: 'split',
    sections: ['hero', 'about', 'features', 'testimonials', 'gallery', 'cta', 'footer'],
    assets: [
      { key: 'portrait', label: 'Portrait', hint: 'Face to camera, natural light', recommendedSections: ['hero', 'about'] },
      { key: 'work', label: 'Work samples', hint: 'What you want to be hired for', recommendedSections: ['gallery'] },
      { key: 'logo', label: 'Signature or wordmark', hint: 'Optional', recommendedSections: ['nav', 'footer'] },
      { key: 'press', label: 'Logos of companies or press', hint: 'Where you have worked or been featured', recommendedSections: ['logos'] },
      { key: 'headshots', label: 'Speaking / in-action photos', hint: 'Stage, studio, on site', recommendedSections: ['gallery', 'about'] },
    ],
  },
  {
    id: 'community',
    label: 'Community',
    emoji: '🫂',
    blurb: 'A group, movement or membership people join.',
    icon: icon('Users'),
    tone: 'inviting, plural, low-friction',
    heroLayout: 'centered',
    sections: ['hero', 'about', 'features', 'stats', 'testimonials', 'schedule', 'cta', 'footer'],
    assets: [
      { key: 'logo', label: 'Community mark', hint: 'Badge, crest or wordmark', recommendedSections: ['nav', 'footer'] },
      { key: 'people', label: 'Member / meetup photos', hint: 'Real people, not stock', recommendedSections: ['hero', 'gallery'] },
      { key: 'screens', label: 'Screenshots of the group in action', hint: 'Discord, Slack, forum', recommendedSections: ['features'] },
      { key: 'events', label: 'Event flyers', hint: 'Past or upcoming', recommendedSections: ['schedule', 'gallery'] },
      { key: 'partners', label: 'Partner logos', hint: 'Who backs you', recommendedSections: ['logos'] },
    ],
  },
  {
    id: 'campaign',
    label: 'Campaign',
    emoji: '📣',
    blurb: 'A cause, drive or launch push with a clear ask.',
    icon: icon('Megaphone'),
    tone: 'urgent, factual, mobilising',
    heroLayout: 'centered',
    sections: ['hero', 'countdown', 'stats', 'about', 'features', 'testimonials', 'waitlist', 'faq', 'footer'],
    assets: [
      { key: 'hero', label: 'Campaign key visual', hint: 'The poster image', recommendedSections: ['hero'] },
      { key: 'field', label: 'Photos from the ground', hint: 'Proof and texture', recommendedSections: ['gallery', 'about'] },
      { key: 'logo', label: 'Organisation logo', hint: 'For trust', recommendedSections: ['nav', 'footer'] },
      { key: 'support', label: 'Supporter / partner logos', hint: 'Endorsements', recommendedSections: ['logos'] },
      { key: 'video', label: 'Film or doc stills', hint: 'Anything with people in it', recommendedSections: ['video'] },
    ],
  },
  {
    id: 'portfolio',
    label: 'Portfolio',
    emoji: '🖼️',
    blurb: 'Studio or freelancer work, shown the right way.',
    icon: icon('Aperture'),
    tone: 'quiet, exacting, visual-first',
    heroLayout: 'fullbleed',
    sections: ['hero', 'gallery', 'about', 'features', 'testimonials', 'contact', 'footer'],
    assets: [
      { key: 'logo', label: 'Studio mark', hint: 'Small and confident', recommendedSections: ['nav', 'footer'] },
      { key: 'projects', label: 'Project images', hint: 'One strong image per project', recommendedSections: ['gallery', 'hero'] },
      { key: 'portrait', label: 'You / the team', hint: 'Optional but disarming', recommendedSections: ['about'] },
      { key: 'detail', label: 'Process or detail shots', hint: 'Sketches, wireframes, prints', recommendedSections: ['gallery'] },
      { key: 'clients', label: 'Client logos', hint: 'Names you can show', recommendedSections: ['logos'] },
    ],
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    emoji: '🍽️',
    blurb: 'Food, drink and a room people want to be in.',
    icon: icon('UtensilsCrossed'),
    tone: 'sensual, hospitable, seasonal',
    heroLayout: 'fullbleed',
    sections: ['hero', 'about', 'menu', 'gallery', 'features', 'testimonials', 'contact', 'footer'],
    assets: [
      { key: 'hero', label: 'Restaurant / hero photo', hint: 'The room at its best hour', recommendedSections: ['hero'] },
      { key: 'food', label: 'Food photos', hint: 'Plates, close, natural light', recommendedSections: ['menu', 'gallery'] },
      { key: 'menu', label: 'Menu images', hint: 'Paper menu is fine', recommendedSections: ['menu'] },
      { key: 'interior', label: 'Interior photos', hint: 'Bar, tables, entrance', recommendedSections: ['gallery', 'about'] },
      { key: 'team', label: 'Chef / team photos', hint: 'Hands at work', recommendedSections: ['about', 'team'] },
    ],
  },
  {
    id: 'other',
    label: 'Other',
    emoji: '✨',
    blurb: 'Something that does not fit a box. We will figure it out.',
    icon: icon('Sparkles'),
    tone: 'open, curious, yours',
    heroLayout: 'centered',
    sections: ['hero', 'about', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    assets: [
      { key: 'logo', label: 'Logo or mark', hint: 'Whatever you have', recommendedSections: ['nav', 'footer'] },
      { key: 'main', label: 'Main image', hint: 'The one you would show first', recommendedSections: ['hero'] },
      { key: 'gallery', label: 'Supporting images', hint: 'Anything that helps the story', recommendedSections: ['gallery'] },
      { key: 'video', label: 'Video', hint: 'Link or upload', recommendedSections: ['video'] },
    ],
  },
];

const SECTION_CATALOG = [
  { type: 'hero', label: 'Hero', description: 'First impression: name, promise, primary action.' },
  { type: 'about', label: 'About', description: 'Who you are and why it exists.' },
  { type: 'features', label: 'Features', description: '3–6 reasons it is worth it.' },
  { type: 'productShowcase', label: 'Product showcase', description: 'Products or plans with images and prices.' },
  { type: 'gallery', label: 'Image gallery', description: 'Your photos, laid out properly.' },
  { type: 'video', label: 'Video', description: 'A film, loop or embed with a caption.' },
  { type: 'pricing', label: 'Pricing', description: 'Tiers, what they include, what to pick.' },
  { type: 'testimonials', label: 'Testimonials', description: 'Quotes from people who came early.' },
  { type: 'countdown', label: 'Countdown', description: 'Live timer to the drop, door or release.' },
  { type: 'waitlist', label: 'Waitlist', description: 'Email capture with position and incentives.' },
  { type: 'contact', label: 'Contact', description: 'Form plus the ways to reach you.' },
  { type: 'faq', label: 'FAQ', description: 'The questions everyone asks.' },
  { type: 'social', label: 'Social links', description: 'Handles and buttons to your profiles.' },
  { type: 'cta', label: 'Call to action', description: 'One last, unmissable ask.' },
  { type: 'newsletter', label: 'Newsletter', description: 'Ongoing capture for updates.' },
  { type: 'footer', label: 'Footer', description: 'Links, legal, credits.' },
  { type: 'logos', label: 'Logo strip', description: 'Press, partners and sponsors.' },
  { type: 'stats', label: 'Stats', description: 'Numbers that make the case.' },
  { type: 'eventDetails', label: 'Event details', description: 'Date, place, time, what to bring.' },
  { type: 'speakers', label: 'Speakers / line-up', description: 'Faces, names and topics.' },
  { type: 'schedule', label: 'Schedule', description: 'Timetable by day.' },
  { type: 'tickets', label: 'Tickets', description: 'Tiers with availability.' },
  { type: 'menu', label: 'Menu', description: 'Dishes and prices.' },
  { type: 'team', label: 'Team', description: 'The people behind it.' },
  { type: 'problem', label: 'Problem', description: 'The gap in the world.' },
  { type: 'solution', label: 'Solution', description: 'How you close it.' },
  { type: 'album', label: 'Release / album', description: 'The record: art, tracklist, credits.' },
  { type: 'tracklist', label: 'Track list', description: 'Song titles and lengths.' },
  { type: 'artistStory', label: 'Artist story', description: 'Origin, sound, where it is going.' },
  { type: 'preSave', label: 'Pre-save / early access', description: 'One tap before release day.' },
];

const WEBSITE_TYPE_IDS = WEBSITE_TYPES.map((t) => t.id);
const typeById = (id) => WEBSITE_TYPES.find((t) => t.id === id) || WEBSITE_TYPES[WEBSITE_TYPE_IDS.length - 1];

module.exports = { WEBSITE_TYPES, SECTION_CATALOG, WEBSITE_TYPE_IDS, typeById };
