/**
 * Demo launches. Each one is generated by the real pipeline (master prompt →
 * compiler → assets → publish), just run at seed time with the images copied
 * in, so the dashboard, the public URLs and the builder all show genuine
 * project data instead of hard-coded mockups.
 */

const DEMO_PROJECTS = [
  {
    key: 'nova',
    slug: 'nova',
    status: 'live',
    name: 'NOVA',
    type: 'product',
    designId: 'futuristic-04',
    description:
      "I'm launching a premium Nigerian streetwear brand called NOVA. Create a futuristic black-and-white website with large product photography, a launch countdown, product information and a waitlist.",
    visualDirection: 'Minimal luxury, black and white, cinematic photography, premium fashion aesthetic.',
    targetAudience: 'people who care about cut, fabric and where a garment was made',
    goal: 'collect waitlist signups before the first drop',
    selectedPlatforms: ['mobile', 'desktop'],
    tagline: 'Lagos-made technical clothing, in runs of 180',
    desiredSections: ['hero', 'countdown', 'productShowcase', 'gallery', 'waitlist'],
    assets: [
      { file: 'nova-campaign.png', slot: 'campaign', description: 'Campaign image for the first drop, shot in the studio in Yaba', caption: 'Drop 01 — shot in Lagos' },
      { file: 'nova-sneaker-1.png', slot: 'product', description: 'Nova Runner in black, product shot for the product section', name: 'Nova Runner — Black' },
      { file: 'nova-sneaker-2.png', slot: 'product', description: 'Nova Runner in bone, second colourway for the product section', name: 'Nova Runner — Bone' },
      { file: 'nova-detail.png', slot: 'detail', description: 'Detail shot of taped seams and ripstop weave for the gallery', caption: 'Taped seams, welded zip' },
    ],
  },
  {
    key: 'afterglow',
    slug: 'afterglow',
    status: 'live',
    name: 'Afterglow',
    type: 'music',
    designId: 'afterhours-18',
    description:
      'A live album by Afterglow, recorded over three nights at Freedom Park Lagos. Moody, film-grain website with the album artwork, the track list, a countdown to release day, a pre-save link and a short artist story.',
    visualDirection: 'Low light, film grain, violet haze, big type, no brightness anywhere.',
    targetAudience: 'people who play records loud and go to small shows',
    goal: 'drive pre-saves before release day',
    selectedPlatforms: ['mobile', 'desktop'],
    tagline: 'Recorded live over three nights at Freedom Park',
    desiredSections: ['hero', 'album', 'tracklist', 'countdown', 'preSave'],
    extraNotes: 'Add the backstage photo to the artist story, not the gallery.',
    assets: [
      { file: 'afterglow-artwork.png', slot: 'artwork', description: 'Artwork for the live album, use it in the release section and the hero', name: 'Afterglow — Live at Freedom Park' },
      { file: 'afterglow-live.png', slot: 'live', description: 'Backstage and stage photos from the three nights, for the artist story', caption: 'Night two, 11:40pm' },
    ],
  },
  {
    key: 'lagos-night',
    slug: 'lagos-night',
    status: 'ready',
    name: 'Lagos Night',
    type: 'event',
    designId: 'festival-07',
    description:
      'Lagos Night is a 1,000-capacity open-air night at Freedom Park on 31 October with four artists, two rooms, a record fair and tickets in three tiers. Bold poster-style website with the line-up, a schedule and FAQ.',
    visualDirection: 'Festival poster energy, black and yellow, stacked names, no corporate polish.',
    targetAudience: 'people who were there last year and told their friends',
    goal: 'sell the remaining standard tickets',
    selectedPlatforms: ['mobile', 'desktop'],
    tagline: 'One night. Two rooms. 1,000 people.',
    desiredSections: ['hero', 'countdown', 'speakers', 'schedule', 'tickets', 'faq'],
    assets: [
      { file: 'lagos-poster.png', slot: 'poster', description: 'The event poster key art, put it in the hero', name: 'Lagos Night 2026 poster' },
      { file: 'afterglow-live.png', slot: 'past', description: 'Photo from last year, for the gallery so people know what to expect', caption: 'Last year, room two' },
    ],
  },
  {
    key: 'shift',
    slug: 'shift',
    status: 'draft',
    name: 'SHIFT',
    type: 'startup',
    designId: 'seed-dark-08',
    description:
      'SHIFT is a technology startup that turns messy meeting notes into tracked, owned actions for operations teams. We need a dark technical site with the problem, the product screenshot, three pricing plans and a demo call to action.',
    visualDirection: 'Technical and precise, near-black, data-forward, mono micro-labels.',
    targetAudience: 'operations leads at 20–200 person companies',
    goal: 'book product demos',
    selectedPlatforms: ['desktop'],
    tagline: 'The action layer for teams that meet too much',
    desiredSections: ['hero', 'problem', 'features', 'pricing'],
    assets: [{ file: 'shift-product.png', slot: 'product', description: 'Screenshot of the SHIFT board with owners and due dates', name: 'SHIFT — action board' }],
  },
];

module.exports = { DEMO_PROJECTS };
